### PR TITLE
fixed unsupported deferred

### PR DESCRIPTION
**Pull request by jensengar**

### CODE REVIEW

**Comment by xdumaine** [comment]
There are other places in the code that use `this.deferred.promise`, so the deferred needs a reference to the promise.

**Comment by xdumaine** [comment]
@jensengar Looks like you have conflicts. Probably the bundle. You can just revert that file. I'll rebundle when I bump version and publish.

**Comment by xdumaine** [comment]
Also let's make it 0.0.2 for now so we don't have to update all of them. When we add some tests we'll minor it.

**Comment by jensengar** [comment]
I set the version to 1.0.0 because that's the bower release version we are using.

**Pull request merged**
